# Generated by Django 3.2.15 on 2022-09-13 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_Producto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=50)),
                ('Categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Id_Proveedor', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Proveedor', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Whatsapp', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Ingresado',
            fields=[
                ('Id_ProductoIngresado', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Valor', models.DecimalField(decimal_places=0, default=0.0, max_digits=8)),
                ('Color', models.CharField(max_length=50)),
                ('Tipo_Material', models.CharField(max_length=50)),
                ('Fecha_Ingreso', models.DateTimeField(auto_now_add=True)),
                ('Id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
                ('Id_Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.proveedor')),
            ],
        ),
    ]
