# Generated by Django 4.1.1 on 2022-09-17 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto_ingresado',
            name='Id_Producto',
        ),
        migrations.AddField(
            model_name='producto_ingresado',
            name='Producto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto_ingresado',
            name='Id_ProductoIngresado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Id_Proveedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='producto_ingresado',
            name='Id_Categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.categoria'),
        ),
    ]
